### ISSUE TITLE
Autocontrast on 14bit Images

### ISSUE THREAD

**Issue by foxsr** [fabrylab/clickpoints#1]
Activating auto contrast mode does not have any effect on 14bit tiff images.
The histogram display in the contrast tool does not seem to work for non 8bit images.

Furthermore, could we add a percentile based auto contrast button, in addition to update / reset button (with cfg setting for the percentile values) ?

[A65_testimage.zip](https://github.com/fabrylab/clickpoints/files/4053411/A65_testimage.zip)

**Comment by rgerum** [comment]
Fixed displaying the histogram 6a496345d1a2598351d238b2c482298eb9b59a98
Autocontrast unfortunately is currently not even implemented.

**Comment by rgerum** [comment]
was a bit harder to implement as expected, as the code was a bit messy. I hope it still works with multiple layers.
