### ISSUE TITLE
In Python 3.8.5 image lists can not be played due Asyncio Problem

### ISSUE THREAD

**Issue by davidbhr** [fabrylab/clickpoints#14]
Image list can be read in but play buttom will result in a "Runtime error: No running event loop" from  line 993 "asyncio.sleep" in clickpoints\modules\timeline.py

**Comment by rgerum** [comment]
Fixed in commit 355dfc2ebf63af90d2c04378e3d9fc620afdc9dc by removing quamash and replacing it with qasync
