### ISSUE TITLE
ImportError: imagecodecs

### ISSUE THREAD

**Issue by AlexanderWinterl** [fabrylab/clickpoints#17]
Why is imagecodecs no dependency?

**Comment by AlexanderWinterl** [comment]
When using tifffile to open a tiff image with jpeg encoding, tiffile breaks with a Value Error'
ValueError: <COMPRESSION.JPEG: 7> requires the 'imagecodecs' package

**Comment by rgerum** [comment]
Yes, you are right, imagecodecs should be a dependency. I added it.
