### ISSUE TITLE
opening mixed 8bit 16bit images & contrast enhancement module

### ISSUE THREAD

**Issue by foxsr** [fabrylab/clickpoints#7]
Random Bug I stumbled across yesterday:

If you open a folder of mixed depth images (e.g. microscope images 16bit + min/maxindex 8bit) by clicking on a 8bit image, displaying the 16bit images will fail:
-> error looking up the bit depth in the LUT -> 20345 out of range 256

If you open the folder by clicking on a 16bit image it works fine (to be confirmed, at least no exception)

**Comment by rgerum** [comment]
Ah well, that is caused by trying to be as fast as possible to load a new image and, therefore, as few checks as possible are performed. But we should at least catch the exception and update the LUT accordingly.

**Comment by foxsr** [comment]
I am aware - I just try to up the issue reporting moral ;)
